### ISSUE TITLE
Error when searching within a collection

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#884]
When searching within a collection (e.g. using the search box on https://era.library.ualberta.ca/collections/44558r66n ), I get a 500 error. The log has:

```
Completed 500 Internal Server Error in 375ms (ActiveRecord: 0.3ms)

NoMethodError (undefined method `[]' for nil:NilClass):
  app/controllers/concerns/hydranorth/collections_controller_behavior.rb:11:in `show'
```
I'm guessing this is something introduced by #868 .

**Comment by mbarnett** [comment]
Bisecting suggests it does appear to have been introduced by #868. Something is going wrong deep inside Blacklight that's causing ```default_search_field``` at https://github.com/projectblacklight/blacklight_advanced_search/blob/master/lib/blacklight_advanced_search/advanced_search_builder.rb#L54-L55 to evaluate to ```nil``` because ```blacklight_config.search_fields``` is empty in ```SearchBuilder``` for these collection search requests post #868.

Right now it's not obvious at all why this would be the case, so this will take some digging to resolve.
